### ISSUE TITLE
Errors when running php setup/setup.php update

### ISSUE THREAD

**Issue by mhilbert** [HochschuleLuzern/SEB#10]
Running "php setup/setup.php update" throws the following error messages:
[ERROR] syntax error, unexpected 'ilSEBConfig' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
[ERROR] syntax error, unexpected 'ilSEBAccessChecker' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
[ERROR] syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST)

The cause are lines 80-83 in classes/class.ilSEBPlugin.php
  private ilSEBConfig $seb_config;
  private ilSEBAccessChecker $access_checker;    
    
  private ?int $current_ref_id;

Commenting out solves the problem successfully running the setup, but possibly adds new problems.

Tested with ILIAS 7.10, SEB 2.6.0, PHP 7.3.31

**Comment by kergomard** [comment]
Hi @mhilbert 
Thank you for reporting this.
Fixed with: https://github.com/HochschuleLuzern/SEB/commit/af181d384db3d994f68be6d7d91c5b346d52cc81
I will try to not forget in the future that ILIAS7 still runs with PHP7.3.
Best,
@swiniker

**Comment by mhilbert** [comment]
That was very fast! Thank you! :+1:
