### ISSUE TITLE
Support for Ilias 6.x / 7.x

### ISSUE THREAD

**Issue by sbaecker** [HochschuleLuzern/SEB#4]
With the upcoming end of life of Ilias 5.4, will there be an update of this plugin to support the recent version(s) of Ilias? Are there any plans or schedules?

Thx

**Comment by kergomard** [comment]
Dear @sbaecker 
Yes, there will be. I'm sorry this is taking me so long. I will need to completely rewrite the plugin, but I also believe that it can now be implemented far more intelligently. I will have it ready latest by the end of the year (EOL ILIAS 5.4).
Best

**Comment by kergomard** [comment]
There is now a version for ILIAS 7. It might work with ILIAS 6, but it is completely untested in this context.
See: https://github.com/HochschuleLuzern/SEB/tree/ilias7
