### ISSUE TITLE
Anzeige der ILIAS-Prüfungsnummer

### ISSUE THREAD

**Issue by mhilbert** [HochschuleLuzern/SEB#6]
Bei aktivierter Option "ILIAS-Prüfungsnummer anzeigen", wird die Prüfungsnummer doppelt angezeigt: einmal in der Metabar und einmal unter dem Seitencontent.
Die Anzeige in der Metabar ist sinnvoll und wünschenswert. Die Anzeige unter dem Seitencontent ist überflüssig und ggf. störend.

**Comment by kergomard** [comment]
Leider kann ich die untere Prüfungsnummer unter der Frage nicht sinnvoll wegputzen, da sie zum Seitencontent gehört  und dieser nicht einfach zugänglich ist. Ich könnte sie nicht in den Header einfügen, aber ich glaube, dass sie da, wie du schreibst, sinnvoll ist.
Sobald wir ein sauberes Konzept haben, wie wir den Seitencontent anpassen können, werde ich sie entfernen. Im Moment würde ich vorschlagen, dass wir halt damit leben, dass sie zwei Mal vorkommt. Einverstanden?

**Comment by mhilbert** [comment]
Einverstanden.

Danke, dass Du's Dir angeschaut hast. Ich hatte auch schon mit CSS und display:none herum experimentiert, bin aber leider auch nicht sauber drangekommen. Man müsste im ILIAS-Core irgendwie eine Element-ID oder eine CSS-Klasse mit reinpatchen, damit man das Element greifen kann, aber das ist mir ein wenig zu dirty, weil ich so wenig wie möglich im Core-Code rumpatchen möchte.

**Comment by kergomard** [comment]
Perfekt. Ja, das Ding ist ein doofes <p>-Tag und auch die darüberliegende Tabelle hat auch keine id und keine Klasse. Ich behalte es im Auge und schliesse diesen Issue. Vielen Dank fürs Melden.
