### ISSUE TITLE
Prüfungsansicht nicht aktivierbar

### ISSUE THREAD

**Issue by mhilbert** [HochschuleLuzern/SEB#7]
Bei installiertem SEB-Plugin ist es in sämtlichen Tests nicht mehr möglich die Option "Prüfungsansicht" zu aktivieren bzw. wird die aktivierte Option beim Speichern wieder zurückgesetzt.

In class.ilSEBPlugin.php findet man zwar die Notiz "We need to switch the kioskmode off in tests to avoid collitions in certain modification providers". Das Verhalten betrifft aber auch Tests, die mit der Standard-Nutzerrolle ohne Nutzung des SEB-Skins ausgeführt werden sollen.

Problematisch ist das Verhalten ebenfalls bei der Nutzung der Option "Weiterleitung nur bei aktivierter Prüfungsansicht".

**Comment by kergomard** [comment]
Kannst du mir erklären, wie du Tests mit und ohne SEB parallel betreiben willst? Ihr könnt natürlich das Plugin so einstellen, dass man auch ohne SEB auf die Plattform kann, dann ist es aber, so weit ich sehen kann, ausser zu Testzwecken komplett sinnlos.
Wenn ich verstehe, werde ich einmal schauen, ob ich eine Lösung finde.

**Comment by mhilbert** [comment]
Unser Prüfungssystem wird zum einen für E-Klausuren genutzt (d.h. Klausuren die vor Ort in einem Prüfungsraum am Rechner geschrieben werden) und zum anderen für Take-Home-Klausuren (d.h. die Prüflinge absolvieren die Tests von zu Hause aus).

Im ersten Fall haben wir lokale, zeitlich beschränkte Accounts (angelegt vom ExamTool), die Nutzer bekommen die globale Rolle "SEB-User" und das SEB-Plugin wird angetriggert (im Zusammenspiel mit dem SafeExamBrowser).
Im zweiten Fall loggen sich die Nutzer mit ihrem LDAP-Account ein und bekommen die globale Standard-Rolle "User". In diesem Fall sollten die Tests in der regulären Prüfungsansicht gestartet werden können.
Die E-Klausuren und Take-Home-Klausuren liegen selbstverständlich in unterschiedlichen rollen- und rechtemäßig voneinander abgetrennten Bereichen.

Bezüglich der Option der Weiterleitung müsste man im aktuellen Fall die Option "Weiterleitung immer zur definierten Zielseite" setzen, damit die Weiterleitung überhaupt funktioniert. Das ist aber störend, wenn man den Test nur durchtesten will und dann jedes Mal ausgeloggt wird.

Mein Vorschlag wäre nicht die Test-Einstellungen zu ändern (das ist aus meiner Sicht auch ziemlich unsauber und führt seitens der Lehrenden auch sicher zu Irritationen, weil es ja intuitiv sinnvoll ist die Prüfungsansicht aktivieren zu wollen), sondern beim aktivierten SEB die Einstellung zu ignorieren.

**Comment by kergomard** [comment]
> Mein Vorschlag wäre nicht die Test-Einstellungen zu ändern (das ist aus meiner Sicht auch ziemlich unsauber und führt seitens der Lehrenden auch sicher zu Irritationen, weil es ja intuitiv sinnvoll ist die Prüfungsansicht aktivieren zu wollen), sondern beim aktivierten SEB die Einstellung zu ignorieren.

Wie stellst du dir das vor? Wir befinden uns in einem Plugin und im Moment sehe ich keinen Weg, wie wir aus der Periferie  (Plugin) dem Zentrum (ILIAS), sagen, was es zu ignorieren hat.

Ich habe aber dein Szenario verstanden und kann dafür sorgen, dass der Haken nur entfernt wird, wenn jemand darauf zugreift, der den SEB-Skin verwendet (verwenden muss).

Ich bin auch damit einverstanden, dass dies nicht die schönste Lösung auf der Welt ist! Nur sehe ich im Moment für ILIAS7 keine schönere.

**Comment by mhilbert** [comment]
Tut mir leid. Bin nicht so tief drin, was die Plugin-Entwicklung angeht und habe daher nicht so den Einblick, was die technischen Einschränkungen angeht.

Ich finde die von Dir vorgeschlagene Lösung aber okay, was die Unterstützung unseres Szenarios angeht. D.h. sobald ein Nutzer mit dem SEB auf den Test zugreift, werden die Test-Einstellungen geändert, ansonsten bleiben sie unangetastet.

Die Weiterleitungsoption muss dann natürlich dennoch auf "Weiterleitung immer zur definierten Zielseite" gestellt werden, damit die Weiterleitung auch bei SEB-Nutzung funktioniert. Das bekomme ich aber kommuniziert.

**Comment by kergomard** [comment]
I've applied the change with: https://github.com/HochschuleLuzern/SEB/commit/0c850d46fa4a81af64a3f25727e431b0b8dd07cc
